import {IUser} from "./iuser";
export interface IAd {
  id: number;
  name: string;
  house_type?: number;
  type: string;
  url: string;
  price: number;
  guests: number;
  bedrooms?: number;
  bathrooms?: number;
  beds?: number;
  amenities?: number[];
  languages?: number[];
  reviews: number;
  rating: number;
  is_instant_book: boolean;
  city?: string;
  about?: string;
  accommodates?: number;
  extra_people?: string;
  cancellation?: string;
  description?: string;
  house_rules?: string;
  minimum_stay?: number;
  author: IUser;
  images: string[];
  current_image: number;
  coordinates: any;
}
